name: Start Cypress Tests
on: [push]

jobs:
 install:
    runs-on: ubuntu-latest
    steps:
    # install the dependencies from the root folder
      - name: Checkout
        uses: actions/checkout@v2.3.6
        
    #run the tests    
      - name: Run Tests
        uses: cypress-io/github-action@v4
        with:
          command: npx cypress run
          browser: chrome
