name: Start Cypress Tests
on:
 push:
   branches:
     - main
jobs:
 Cypress-Test:
   runs-on: ubuntu-latest
   steps:
     - name: Run Tests
       uses: cypress-io/github-action@v4
       with:
         command: npx cypress run
         browser: chrome
